name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Test
        run: make
      - name: Valgrind
        run: |
          sudo apt-get install -y valgrind
          valgrind --leak-check=full --error-exitcode=1 ./simple_options_test
